{% set name = "trame" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-{{ version }}.tar.gz
  sha256: 226673f828f9b99c12a3c38b775d84eadd1d4b0482bfc13fc747a4bc1c748df7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-client >=2.1.0
    - trame-components
    - trame-deckgl
    - trame-markdown
    - trame-matplotlib
    - trame-plotly
    - trame-rca
    - trame-router
    - trame-server >=2.1.0
    - trame-simput
    - trame-vega
    - trame-vtk
    - trame-vuetify

test:
  imports:
    - trame
    - trame.app
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame/
  summary: Trame, a framework to build applications in plain Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
