{% set name = "trame" %}
{% set version = "3.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-{{ version }}.tar.gz
  sha256: 85b24e4a83cc9cb61854f55db2d5ace8b58468b31f696fa19e576487f62e4152

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-server >=2.11.0
    - trame-client >=2.7.7
    - trame-components <3.0.0
    - trame-deckgl <3.0.0
    - trame-markdown <3.0.0
    - trame-matplotlib <3.0.0
    - trame-plotly <3.0.0
    - trame-rca <3.0.0
    - trame-router <3.0.0
    - trame-simput <3.0.0
    - trame-vega <3.0.0
    - trame-vtk <3.0.0
    - trame-vuetify <3.0.0

test:
  imports:
    - trame
    - trame.app
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame/
  summary: Trame, a framework to build applications in plain Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
