{% set name = "trame" %}
{% set version = "3.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame-{{ version }}.tar.gz
  sha256: 9868d1c2bce981ae2c66eb6a16d39e2a14f042eedb1047666266c753ecaf3f64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - trame-server >=3.12.1
    - trame-client >=3.12.2
    - trame-common >=1.2.3
    - pyyaml

test:
  imports:
    - trame
    - trame.app
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/trame/
  summary: Trame, a framework to build applications in plain Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - jourdain
    - psavery
    - kwrobot
