{% set name = "trame" %}
{% set version = "3.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-{{ version }}.tar.gz
  sha256: c2cc3c81b6be2b480584ecf789397e0925896b0d94eb8e807ae847e91e3b8850

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-server >=2.13.1
    - trame-client >=2.14.0

test:
  imports:
    - trame
    - trame.app
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame/
  summary: Trame, a framework to build applications in plain Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
